server:
  port: 5858

spring :
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: root
    password: sixxrasz60!@

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
        format_sql: true
        ddl-auto: update

  profiles:
    include: oauth

  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: samik.hestia.502@gmail.com
    password: ugxrrvsabdiivviz
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 5000